# Generated by Django 3.0.6 on 2020-05-25 14:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first', models.CharField(max_length=225)),
                ('contact_last', models.CharField(max_length=225)),
                ('contact_email', models.CharField(max_length=225)),
                ('contact_subject', models.CharField(max_length=225)),
                ('contact_feedback', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=225)),
                ('job_email', models.CharField(max_length=225)),
                ('job_country', models.CharField(max_length=225)),
                ('job_contact', models.IntegerField(default=0)),
                ('job_tech', models.CharField(max_length=225)),
                ('job_exp', models.IntegerField(default=0)),
                ('job_company', models.CharField(max_length=225)),
                ('job_qual', models.CharField(max_length=225)),
                ('job_resume', models.FileField(null=True, upload_to='resume')),
            ],
        ),
        migrations.CreateModel(
            name='UProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='pics')),
                ('dob', models.DateTimeField(null=True)),
                ('desc', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=10000)),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
