# Generated by Django 3.0.6 on 2020-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_contact',
            field=models.BigIntegerField(default=0),
        ),
    ]
