# Generated by Django 3.0.6 on 2020-06-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_discussion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
