# Generated by Django 3.0.6 on 2020-06-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_delete_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='reply',
            new_name='parent',
        ),
    ]
