# Generated by Django 3.0.6 on 2020-06-06 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20200602_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_contact',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Enter in format +9999999999. Upto 15 Digits allowed', regex='^\\+?1?\\d{10, 15}$')]),
        ),
    ]
