# Generated by Django 3.0.6 on 2020-06-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_auto_20200606_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_contact',
            field=models.BigIntegerField(default=0),
        ),
    ]
